### ISSUE TITLE
Ensure the plugin meets the Unreal Marketplace guidelines

### ISSUE THREAD

**Issue by nfrechette** [nfrechette/acl-ue4-plugin#25]
The guidelines can be found here: https://www.unrealengine.com/en-US/marketplace-guidelines

- [x] Move ThirdParty directory under Source
- [x] Make sure we use `PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;`
- [x] Add the Public path for the public headers in .cs file, see [here](https://www.unrealengine.com/en-US/marketplace-guidelines#263e)
- [x] Add empty black list, see [here](https://www.unrealengine.com/en-US/marketplace-guidelines#261b)
- [x] Add engine version to uplugin, see [here](https://www.unrealengine.com/en-US/marketplace-guidelines#261a)
- [x] Add UE shield `![UE4](https://img.shields.io/badge/UE4-4.25%2B-orange)`
- [x] Double check linked sample project
- [x] Run the plugin `Package ...` action, see [here](https://www.unrealengine.com/en-US/marketplace-guidelines#263b)
- [x] Rename the plugin to the full ACL name for clarity in the plugin window
- [x] Remove the `IsBeta` flag from uplugin
- [x] Revisit and update the documentation
- [x] Update the stats with UE 4.25
- [x] Ensure FilterPlugin.ini is present and the README and LICENSE are included, see [here](https://www.unrealengine.com/en-US/marketplace-guidelines#273b)
- [x] Update icon to something appropriate (128x128 PNG)
- [x] Set the marketplace URL, see [here](https://www.unrealengine.com/en-US/marketplace-guidelines#261c)

See [here](https://github.com/PipeRift/ActionsExtension/blob/master/ActionsExtension.uplugin) for an example.

**Comment by nfrechette** [comment]
`Package ...` requires remote iOS compilation. See [here](https://docs.unrealengine.com/en-US/Platforms/Mobile/iOS/Windows/index.html) for setup instructions.

**Comment by nfrechette** [comment]
Done!
